FROM node:11.2-alpine

WORKDIR /code

ADD /src/main/resources /code/src/main/resources

# Compile front-end
WORKDIR /code/src/main/resources

RUN npm install -g @angular/cli
RUN npm install
RUN ng build

EXPOSE 4200
